language: csharp
mono: none
sudo: required
dotnet: 3.0.100

os:
  - linux

env:
  - XNuGetApiKeyName="X-NuGet-ApiKey:"

install:
  - dotnet restore

before_script:
  - BUILD_HASH=`git log --pretty=format:%h -n 1`
  - "echo \"Build number: $TRAVIS_BUILD_NUMBER-$BUILD_HASH\""

script:
  - set -e

  - echo "travis_fold:start:Build"
  - dotnet build -c $BUILD_CONFIGURATION --no-restore
  - echo "travis_fold:end:Build"

  - echo "travis_fold:start:Test"
  - dotnet test -c $BUILD_CONFIGURATION -f netcoreapp3.0 --no-restore --no-build
  - echo "travis_fold:end:Test"

  - echo "travis_fold:start:Pack"
  - dotnet pack -c $BUILD_CONFIGURATION --no-restore --no-build --version-suffix=-alfa-$TRAVIS_BUILD_NUMBER-$BUILD_HASH
  - echo "travis_fold:end:Pack"

after_success:
  - for file in "./src/Anteater.Pipe/bin/$BUILD_CONFIGURATION/*.nupkg";
      do curl -X POST "$MYGET_NUGET_URL" -H "$XNuGetApiKeyName $MYGET_NUGET_APIKEY" -T $file;
    done;

