image: microsoft/dotnet:latest
pipelines:
  default:
    - step:
        name: Build, Test, Publish
        caches:          
          - dotnetcore
        script:
          # Generate build number
          - BUILD_HASH=`git log --pretty=format:%h -n 1`
          - echo "Build number':' ${BITBUCKET_BUILD_NUMBER}-${BUILD_HASH}"
          # Restore packages
          # - dotnet restore
          # Build project
          # - dotnet build
          # Run tests
          - dotnet test ./test/Anteater.Pipe.Tests
          # Create package
          - dotnet pack --configuration ${BUILD_CONFIGURATION} --version-suffix=-alfa-$BITBUCKET_BUILD_NUMBER-$BUILD_HASH
          # Push generated package(s)
          - "for file in ./src/Anteater.Pipe/bin/${BUILD_CONFIGURATION}/*.nupkg; do curl -X POST \"${MYGET_NUGET_URL}\" -H \"X-NuGet-ApiKey: ${MYGET_NUGET_APIKEY}\" -T $file; done"
