name: Build, test and pack

on: [push]

env:
  BUILD_CONFIGURATION: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        framework: [netcoreapp2.2, netcoreapp3.0]

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.402

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100

      - run: rsync -a ${DOTNET_ROOT/3.0.100/2.2.402}/* $DOTNET_ROOT/

      - name: Test
        run: dotnet test -c ${BUILD_CONFIGURATION} -f ${{ matrix.framework }}
      
  pack:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100

      - uses: einaregilsson/build-number@v2 
        with:
          token: ${{ secrets.github_token }}

      - name: Generate build number
        run: echo "::set-env name=BUILD_HASH::`git log --pretty=format:%h -n 1`"

      - name: Pack nuget package
        run: dotnet pack -c $BUILD_CONFIGURATION --version-suffix=-alfa-$BUILD_NUMBER-$BUILD_HASH -o ./out

      - name: Publish
        if: success()
        run: nuget push ./out/Anteater.Pipe.1.0.0-alfa-$BUILD_NUMBER-$BUILD_HASH.nupkg ${{ secrets.MYGET_NUGET_APIKEY }} -src https://www.myget.org/F/anteater/api/v2/package
