name: test

on:
  push:
    branches-ignore:
      - master
      - 'releases/**'

env:
  BUILD_CONFIGURATION: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        framework: [netcoreapp3.1, net5.0]

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101

      - run: rsync -a ${DOTNET_ROOT/3.1.100/5.0.101}/* $DOTNET_ROOT/

      - name: Test
        run: dotnet test -c ${{ env.BUILD_CONFIGURATION }} -f ${{ matrix.framework }}
